// AUTO-GENERATED — droid portraits extracted from in-game Droidex screenshots.
// One folder per droid under public/droids/<slug>/<rarity>.png
import type { CollectionSlot } from './types'

export const droidImages: Record<
  string,
  Partial<Record<CollectionSlot, string>>
> = {
  Mouse: {
    Basic: 'mouse/basic.png',
    Gold: 'mouse/gold.png',
    Diamond: 'mouse/diamond.png',
    Rainbow: 'mouse/rainbow.png',
    Beskar: 'mouse/beskar.png',
  },
  PIT: {
    Basic: 'pit/basic.png',
    Gold: 'pit/gold.png',
    Diamond: 'pit/diamond.png',
    Rainbow: 'pit/rainbow.png',
    Beskar: 'pit/beskar.png',
  },
  Gonk: {
    Basic: 'gonk/basic.png',
    Gold: 'gonk/gold.png',
    Diamond: 'gonk/diamond.png',
    Rainbow: 'gonk/rainbow.png',
    Beskar: 'gonk/beskar.png',
  },
  CB: {
    Basic: 'cb/basic.png',
    Gold: 'cb/gold.png',
    Diamond: 'cb/diamond.png',
    Rainbow: 'cb/rainbow.png',
    Beskar: 'cb/beskar.png',
  },
  R3: {
    Basic: 'r3/basic.png',
    Gold: 'r3/gold.png',
    Diamond: 'r3/diamond.png',
    Rainbow: 'r3/rainbow.png',
    Beskar: 'r3/beskar.png',
  },
  R5: {
    Basic: 'r5/basic.png',
    Gold: 'r5/gold.png',
    Diamond: 'r5/diamond.png',
    Rainbow: 'r5/rainbow.png',
    Beskar: 'r5/beskar.png',
  },
  R8: {
    Basic: 'r8/basic.png',
    Gold: 'r8/gold.png',
    Diamond: 'r8/diamond.png',
    Rainbow: 'r8/rainbow.png',
    Beskar: 'r8/beskar.png',
  },
  'Imperial Probe': {
    Basic: 'imperial-probe/basic.png',
    Gold: 'imperial-probe/gold.png',
    Diamond: 'imperial-probe/diamond.png',
    Rainbow: 'imperial-probe/rainbow.png',
    Beskar: 'imperial-probe/beskar.png',
  },
  'B1 Battle': {
    Basic: 'b1-battle/basic.png',
    Gold: 'b1-battle/gold.png',
    Diamond: 'b1-battle/diamond.png',
    Rainbow: 'b1-battle/rainbow.png',
    Beskar: 'b1-battle/beskar.png',
  },
  'DRK-1 Probe': {
    Basic: 'drk-1-probe/basic.png',
    Gold: 'drk-1-probe/gold.png',
    Diamond: 'drk-1-probe/diamond.png',
    Rainbow: 'drk-1-probe/rainbow.png',
    Beskar: 'drk-1-probe/beskar.png',
  },
  ID10: {
    Basic: 'id10/basic.png',
    Gold: 'id10/gold.png',
    Diamond: 'id10/diamond.png',
    Rainbow: 'id10/rainbow.png',
    Beskar: 'id10/beskar.png',
  },
  'BDX Explorer': {
    Basic: 'bdx-explorer/basic.png',
    Gold: 'bdx-explorer/gold.png',
    Diamond: 'bdx-explorer/diamond.png',
    Rainbow: 'bdx-explorer/rainbow.png',
    Beskar: 'bdx-explorer/beskar.png',
  },
  ARG: {
    Basic: 'arg/basic.png',
    Gold: 'arg/gold.png',
    Diamond: 'arg/diamond.png',
    Rainbow: 'arg/rainbow.png',
    Beskar: 'arg/beskar.png',
  },
  'Senate Hovercam': {
    Basic: 'senate-hovercam/basic.png',
    Gold: 'senate-hovercam/gold.png',
    Diamond: 'senate-hovercam/diamond.png',
    Rainbow: 'senate-hovercam/rainbow.png',
    Beskar: 'senate-hovercam/beskar.png',
  },
  'BU-4D': {
    Basic: 'bu-4d/basic.png',
    Gold: 'bu-4d/gold.png',
    Diamond: 'bu-4d/diamond.png',
    Rainbow: 'bu-4d/rainbow.png',
    Beskar: 'bu-4d/beskar.png',
  },
  'BAL-Core': {
    Basic: 'bal-core/basic.png',
    Gold: 'bal-core/gold.png',
    Diamond: 'bal-core/diamond.png',
    Rainbow: 'bal-core/rainbow.png',
    Beskar: 'bal-core/beskar.png',
  },
  'ROLL-R': {
    Basic: 'roll-r/basic.png',
    Gold: 'roll-r/gold.png',
    Diamond: 'roll-r/diamond.png',
    Rainbow: 'roll-r/rainbow.png',
    Beskar: 'roll-r/beskar.png',
  },
  '2BB': {
    Basic: '2bb/basic.png',
    Gold: '2bb/gold.png',
    Diamond: '2bb/diamond.png',
    Rainbow: '2bb/rainbow.png',
    Beskar: '2bb/beskar.png',
  },
  'A-LT': {
    Basic: 'a-lt/basic.png',
    Gold: 'a-lt/gold.png',
    Diamond: 'a-lt/diamond.png',
    Rainbow: 'a-lt/rainbow.png',
    Beskar: 'a-lt/beskar.png',
  },
  R4: {
    Basic: 'r4/basic.png',
    Gold: 'r4/gold.png',
    Diamond: 'r4/diamond.png',
    Rainbow: 'r4/rainbow.png',
    Beskar: 'r4/beskar.png',
  },
  R9: {
    Basic: 'r9/basic.png',
    Gold: 'r9/gold.png',
    Diamond: 'r9/diamond.png',
    Rainbow: 'r9/rainbow.png',
    Beskar: 'r9/beskar.png',
  },
  'B1 Security': {
    Basic: 'b1-security/basic.png',
    Gold: 'b1-security/gold.png',
    Diamond: 'b1-security/diamond.png',
    Rainbow: 'b1-security/rainbow.png',
    Beskar: 'b1-security/beskar.png',
  },
  'NAV-EX': {
    Basic: 'nav-ex/basic.png',
    Gold: 'nav-ex/gold.png',
    Diamond: 'nav-ex/diamond.png',
    Rainbow: 'nav-ex/rainbow.png',
    Beskar: 'nav-ex/beskar.png',
  },
  'VECT-ARM': {
    Basic: 'vect-arm/basic.png',
    Gold: 'vect-arm/gold.png',
    Diamond: 'vect-arm/diamond.png',
    Rainbow: 'vect-arm/rainbow.png',
    Beskar: 'vect-arm/beskar.png',
  },
  'HOV-R': {
    Basic: 'hov-r/basic.png',
    Gold: 'hov-r/gold.png',
    Diamond: 'hov-r/diamond.png',
    Rainbow: 'hov-r/rainbow.png',
    Beskar: 'hov-r/beskar.png',
  },
  Groundmech: {
    Basic: 'groundmech/basic.png',
    Gold: 'groundmech/gold.png',
    Diamond: 'groundmech/diamond.png',
    Rainbow: 'groundmech/rainbow.png',
    Beskar: 'groundmech/beskar.png',
  },
  LO: {
    Basic: 'lo/basic.png',
    Gold: 'lo/gold.png',
    Diamond: 'lo/diamond.png',
    Rainbow: 'lo/rainbow.png',
    Beskar: 'lo/beskar.png',
  },
  'AMP Walker': {
    Basic: 'amp-walker/basic.png',
    Gold: 'amp-walker/gold.png',
    Diamond: 'amp-walker/diamond.png',
    Rainbow: 'amp-walker/rainbow.png',
    Beskar: 'amp-walker/beskar.png',
  },
  'SEN-TRI': {
    Basic: 'sen-tri/basic.png',
    Gold: 'sen-tri/gold.png',
    Diamond: 'sen-tri/diamond.png',
    Rainbow: 'sen-tri/rainbow.png',
    Beskar: 'sen-tri/beskar.png',
  },
  'OPTI-Pod': {
    Basic: 'opti-pod/basic.png',
    Gold: 'opti-pod/gold.png',
    Diamond: 'opti-pod/diamond.png',
    Rainbow: 'opti-pod/rainbow.png',
    Beskar: 'opti-pod/beskar.png',
  },
  Gunrunner: {
    Basic: 'gunrunner/basic.png',
    Gold: 'gunrunner/gold.png',
    Diamond: 'gunrunner/diamond.png',
    Rainbow: 'gunrunner/rainbow.png',
    Beskar: 'gunrunner/beskar.png',
  },
  BB: {
    Basic: 'bb/basic.png',
    Gold: 'bb/gold.png',
    Diamond: 'bb/diamond.png',
    Rainbow: 'bb/rainbow.png',
    Beskar: 'bb/beskar.png',
  },
  R2: {
    Basic: 'r2/basic.png',
    Gold: 'r2/gold.png',
    Diamond: 'r2/diamond.png',
    Rainbow: 'r2/rainbow.png',
    Beskar: 'r2/beskar.png',
  },
  R6: {
    Basic: 'r6/basic.png',
    Gold: 'r6/gold.png',
    Diamond: 'r6/diamond.png',
    Rainbow: 'r6/rainbow.png',
    Beskar: 'r6/beskar.png',
  },
  'TRAK-R': {
    Basic: 'trak-r/basic.png',
    Gold: 'trak-r/gold.png',
    Diamond: 'trak-r/diamond.png',
    Rainbow: 'trak-r/rainbow.png',
    Beskar: 'trak-r/beskar.png',
  },
  'Orb-Walker': {
    Basic: 'orb-walker/basic.png',
    Gold: 'orb-walker/gold.png',
    Diamond: 'orb-walker/diamond.png',
    Rainbow: 'orb-walker/rainbow.png',
    Beskar: 'orb-walker/beskar.png',
  },
  'UTIL-TEC': {
    Basic: 'util-tec/basic.png',
    Gold: 'util-tec/gold.png',
    Diamond: 'util-tec/diamond.png',
    Rainbow: 'util-tec/rainbow.png',
    Beskar: 'util-tec/beskar.png',
  },
  'B1 Heavy': {
    Basic: 'b1-heavy/basic.png',
    Gold: 'b1-heavy/gold.png',
    Diamond: 'b1-heavy/diamond.png',
    Rainbow: 'b1-heavy/rainbow.png',
    Beskar: 'b1-heavy/beskar.png',
  },
  'B2 Super': {
    Basic: 'b2-super/basic.png',
    Gold: 'b2-super/gold.png',
    Diamond: 'b2-super/diamond.png',
    Rainbow: 'b2-super/rainbow.png',
    Beskar: 'b2-super/beskar.png',
  },
  'B2 Heavy': {
    Basic: 'b2-heavy/basic.png',
    Gold: 'b2-heavy/gold.png',
    Diamond: 'b2-heavy/diamond.png',
    Rainbow: 'b2-heavy/rainbow.png',
    Beskar: 'b2-heavy/beskar.png',
  },
  'Strike-Orb': {
    Basic: 'strike-orb/basic.png',
    Gold: 'strike-orb/gold.png',
    Diamond: 'strike-orb/diamond.png',
    Rainbow: 'strike-orb/rainbow.png',
    Beskar: 'strike-orb/beskar.png',
  },
  'HAUL-R': {
    Basic: 'haul-r/basic.png',
    Gold: 'haul-r/gold.png',
    Diamond: 'haul-r/diamond.png',
    Rainbow: 'haul-r/rainbow.png',
    Beskar: 'haul-r/beskar.png',
  },
  'LNG-Shot': {
    Basic: 'lng-shot/basic.png',
    Gold: 'lng-shot/gold.png',
    Diamond: 'lng-shot/diamond.png',
    Rainbow: 'lng-shot/rainbow.png',
    Beskar: 'lng-shot/beskar.png',
  },
  'Proto-Roller': {
    Basic: 'proto-roller/basic.png',
    Gold: 'proto-roller/gold.png',
    Diamond: 'proto-roller/diamond.png',
    Rainbow: 'proto-roller/rainbow.png',
    Beskar: 'proto-roller/beskar.png',
  },
  'Mecha-Droid': {
    Basic: 'mecha-droid/basic.png',
    Gold: 'mecha-droid/gold.png',
    Diamond: 'mecha-droid/diamond.png',
    Rainbow: 'mecha-droid/rainbow.png',
    Beskar: 'mecha-droid/beskar.png',
  },
  'Mono-Walker': {
    Basic: 'mono-walker/basic.png',
    Gold: 'mono-walker/gold.png',
    Diamond: 'mono-walker/diamond.png',
    Rainbow: 'mono-walker/rainbow.png',
    Beskar: 'mono-walker/beskar.png',
  },
  BB9: {
    Basic: 'bb9/basic.png',
    Gold: 'bb9/gold.png',
    Diamond: 'bb9/diamond.png',
    Rainbow: 'bb9/rainbow.png',
    Beskar: 'bb9/beskar.png',
  },
  R7: {
    Basic: 'r7/basic.png',
    Gold: 'r7/gold.png',
    Diamond: 'r7/diamond.png',
    Rainbow: 'r7/rainbow.png',
    Beskar: 'r7/beskar.png',
  },
  'B2-RP': {
    Basic: 'b2-rp/basic.png',
    Gold: 'b2-rp/gold.png',
    Diamond: 'b2-rp/diamond.png',
    Rainbow: 'b2-rp/rainbow.png',
    Beskar: 'b2-rp/beskar.png',
  },
  'Cyclo-Grav': {
    Basic: 'cyclo-grav/basic.png',
    Gold: 'cyclo-grav/gold.png',
    Diamond: 'cyclo-grav/diamond.png',
    Rainbow: 'cyclo-grav/rainbow.png',
    Beskar: 'cyclo-grav/beskar.png',
  },
  'OPTI-Strike': {
    Basic: 'opti-strike/basic.png',
    Gold: 'opti-strike/gold.png',
    Diamond: 'opti-strike/diamond.png',
    Rainbow: 'opti-strike/rainbow.png',
    Beskar: 'opti-strike/beskar.png',
  },
  BB8: {
    Basic: 'bb8/basic.png',
  },
  'Mister Bones': {
    Basic: 'mister-bones/basic.png',
  },
  'IG-11 Marshal': {
    Basic: 'ig-11-marshal/basic.png',
  },
  'DJ-R3X': {
    Basic: 'dj-r3x/basic.png',
  },
  'CB-23': {
    Basic: 'cb-23/basic.png',
  },
}
